remote_theme: "mmistakes/minimal-mistakes@4.15.2"
minimal_mistakes_skin: "default"

locale: "en-US"
title: TechCentrix SDK
description: Integrate with our LED technology in few steps

plugins:
  - jekyll-include-cache
  - jekyll-analytics

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: splash
      sidebar:
        nav: "docs"

jekyll_analytics:
  GoogleAnalytics:
    id: UA—136787524-4
    anonymizeIp: false
